#ifndef SRC_SERVER_API_HANDLER_H_
#define SRC_SERVER_API_HANDLER_H_

#include <map>
#include <string>
#include <string_view>

#include "src/server/net/http_handler.h"
#include "src/server/net/http_req_target.h"
#include "src/server/util/status.h"
#include "src/server/util/status_or.h"

namespace server {

// Handles API requests. The app currently supports API requests of form:
//
//   GET /api/album?path=
//   GET /api/album?path=Travel
//   GET /api/album?path=Travel/Iceland
//
// At each directory level, the API responds with a JSON of the directory
// contents, which are either sub-albums, or photos with metadata. Example:
//
//   {
//     "path": "Travel",
//     "entries": [
//       { type: "album", "name": "Iceland" },
//       { type: "album", "name": "Japan" },
//       { type: "photo", "name": "cover.jpg", "stereo": "gphoto" }
//     ]
//   }
//
// Currently supported stereo layouts for media are
//
// - "gphoto": Google's VR photo format, which has the left eye in the JPEG
//   data, the right eye in the XMP metadata as base64-encoded JPEG.
//   https://developers.google.com/vr/reference/cardboard-camera-vr-photo-format
// - "sbs": Side-by-side photo or video format, where the left and right eyes
//   are stored in the same image, left and right halves are the eyes.
// - "geometry": Not really a stereo format. Stereo is generated by rendering
//   the geometry twice, once for each eye.
//
class ApiHandler : public net::HttpHandlerBase {
 public:
  struct Options {
    std::string media_root;
    std::map<std::string, std::string> reply_headers;
  };

  explicit ApiHandler(const Options& options);

 protected:
  util::Status Handle(net::HttpRequest& request) const override;
  util::Status HandleAlbumRequest(net::HttpRequest& request,
                                  const net::HttpReqTarget& target) const;

 private:
  util::StatusOr<std::string> GetLocalPath(std::string_view req_path) const;

  const Options options_;
};

}  // namespace server

#endif  // SRC_SERVER_API_HANDLER_H_
